version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "daily"
