// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/server_handshake.proto

package com.husbylabs.hawkeye.packets;

public final class ServerHandshakeOuterClass {
    private ServerHandshakeOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ServerHandshakeOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ServerHandshake)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 protocol = 1;</code>
         *
         * @return The protocol.
         */
        int getProtocol();

        /**
         * <code>bool compatible = 2;</code>
         *
         * @return The compatible.
         */
        boolean getCompatible();
    }

    /**
     * Protobuf type {@code ServerHandshake}
     */
    public static final class ServerHandshake extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ServerHandshake)
            ServerHandshakeOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ServerHandshake.newBuilder() to construct.
        private ServerHandshake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ServerHandshake() {
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ServerHandshake();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ServerHandshake(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            protocol_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            compatible_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.internal_static_ServerHandshake_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.internal_static_ServerHandshake_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.class, com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.Builder.class);
        }

        public static final int PROTOCOL_FIELD_NUMBER = 1;
        private int protocol_;

        /**
         * <code>int32 protocol = 1;</code>
         *
         * @return The protocol.
         */
        @java.lang.Override
        public int getProtocol() {
            return protocol_;
        }

        public static final int COMPATIBLE_FIELD_NUMBER = 2;
        private boolean compatible_;

        /**
         * <code>bool compatible = 2;</code>
         *
         * @return The compatible.
         */
        @java.lang.Override
        public boolean getCompatible() {
            return compatible_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (protocol_ != 0) {
                output.writeInt32(1, protocol_);
            }
            if (compatible_ != false) {
                output.writeBool(2, compatible_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (protocol_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, protocol_);
            }
            if (compatible_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, compatible_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake)) {
                return super.equals(obj);
            }
            com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake other = (com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake) obj;

            if (getProtocol()
                != other.getProtocol()) {
                return false;
            }
            if (getCompatible()
                != other.getCompatible()) {
                return false;
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
            hash = (53 * hash) + getProtocol();
            hash = (37 * hash) + COMPATIBLE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getCompatible());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServerHandshake}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ServerHandshake)
                com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshakeOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.internal_static_ServerHandshake_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.internal_static_ServerHandshake_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.class, com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.Builder.class);
            }

            // Construct using com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                protocol_ = 0;

                compatible_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.internal_static_ServerHandshake_descriptor;
            }

            @java.lang.Override
            public com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake getDefaultInstanceForType() {
                return com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.getDefaultInstance();
            }

            @java.lang.Override
            public com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake build() {
                com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake buildPartial() {
                com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake result = new com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake(this);
                result.protocol_ = protocol_;
                result.compatible_ = compatible_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake) {
                    return mergeFrom((com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake other) {
                if (other == com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake.getDefaultInstance()) {
                    return this;
                }
                if (other.getProtocol() != 0) {
                    setProtocol(other.getProtocol());
                }
                if (other.getCompatible() != false) {
                    setCompatible(other.getCompatible());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int protocol_;

            /**
             * <code>int32 protocol = 1;</code>
             *
             * @return The protocol.
             */
            @java.lang.Override
            public int getProtocol() {
                return protocol_;
            }

            /**
             * <code>int32 protocol = 1;</code>
             *
             * @param value The protocol to set.
             * @return This builder for chaining.
             */
            public Builder setProtocol(int value) {

                protocol_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 protocol = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearProtocol() {

                protocol_ = 0;
                onChanged();
                return this;
            }

            private boolean compatible_;

            /**
             * <code>bool compatible = 2;</code>
             *
             * @return The compatible.
             */
            @java.lang.Override
            public boolean getCompatible() {
                return compatible_;
            }

            /**
             * <code>bool compatible = 2;</code>
             *
             * @param value The compatible to set.
             * @return This builder for chaining.
             */
            public Builder setCompatible(boolean value) {

                compatible_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool compatible = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCompatible() {

                compatible_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ServerHandshake)
        }

        // @@protoc_insertion_point(class_scope:ServerHandshake)
        private static final com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake();
        }

        public static com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ServerHandshake>
                PARSER = new com.google.protobuf.AbstractParser<ServerHandshake>() {
            @java.lang.Override
            public ServerHandshake parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServerHandshake(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ServerHandshake> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ServerHandshake> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.husbylabs.hawkeye.packets.ServerHandshakeOuterClass.ServerHandshake getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ServerHandshake_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ServerHandshake_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\035protos/server_handshake.proto\"7\n\017Serve" +
                "rHandshake\022\020\n\010protocol\030\001 \001(\005\022\022\n\ncompatib" +
                "le\030\002 \001(\010B\037\n\035com.husbylabs.hawkeye.packet" +
                "sb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_ServerHandshake_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ServerHandshake_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ServerHandshake_descriptor,
                new java.lang.String[]{ "Protocol", "Compatible", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
