name: Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Make gradlew executable
      working-directory: ./java
      run: chmod +x ./gradlew
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Build with Gradle
      working-directory: ./java
      run: ./gradlew build
